### ISSUE TITLE
Remote logging python script ascii decoder

### ISSUE THREAD

**Issue by mibas74** [shmuelzon/esp32-ble2mqtt#64]
Hi,
because I see that my esp32 boards stops to receive data from Xiaomi Temperature and Humidity sensors (seems as BLE issue, because mqtt messages are still received by mosquitto broker) I've started remote logging script and quickly even the logging script stopped work:

`2019-12-21 15:04:02.420331 (BLE2MQTT-8264.lan): I (89072) BLE2MQTT: Publishing: 58:2d:34:37:20:cc/DeviceInformation/ModelNumberString = Duck_Release
Traceback (most recent call last):
  File "remote_log.py", line 66, in <module>    main()
  File "remote_log.py", line 63, in main  log_listener(args)
  File "remote_log.py", line 41, in log_listener data.decode()), end='')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 101: ordinal not in range(128)
`

`2019-12-21 15:15:28.816169 (BLE2MQTT-8264.lan): I (221062) BLE2MQTT: Publishing: 58:2d:34:36:1e:97/DeviceInformation/ModelNumberString = Duck_Release
Traceback (most recent call last):
  File "remote_log.py", line 66, in <module>
    main()
  File "remote_log.py", line 63, in main
    log_listener(args)
  File "remote_log.py", line 41, in log_listener
    data.decode()), end='')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x97 in position 102: ordinal not in range(128)
`

`2019-12-21 15:17:28.936612 (BLE2MQTT-8264.lan): I (341182) BLE2MQTT: Publishing: 58:2d:34:37:20:cc/DeviceInformation/ModelNumberString = Duck_Release
Traceback (most recent call last):
  File "remote_log.py", line 66, in <module>
    main()
  File "remote_log.py", line 63, in main
    log_listener(args)
  File "remote_log.py", line 41, in log_listener
    data.decode()), end='')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 102: invalid continuation byte
`
`2019-12-21 15:19:00.282369 (BLE2MQTT-8264.lan): I (432532) BLE2MQTT: Discovered Mijia Temp+Hum broadcaster
2019-12-21 15:19:00.300547 (BLE2MQTT-8264.lan): I (432552) BLE2MQTT: Discovered BLE device: 58:2d:34:36:18:9c (RSSI: -77), connecting
2019-12-21 15:19:06.828079 (BLE2MQTT-8264.lan): I (439072) BLE2MQTT: Connected to device: 58:2d:34:36:18:9c, scanning
2019-12-21 15:19:07.486785 (BLE2MQTT-8264.lan): I (439732) BLE2MQTT: Publishing: 58:2d:34:36:18:9c/GenericAccess/DeviceName = MJ_HT_V1
2019-12-21 15:19:07.538681 (BLE2MQTT-8264.lan): I (439782) BLE2MQTT: Publishing: 58:2d:34:36:18:9c/GenericAccess/Appearance = 768
2019-12-21 15:19:07.606605 (BLE2MQTT-8264.lan): I (439852) BLE2MQTT: Publishing: 58:2d:34:36:18:9c/GenericAccess/PeripheralPreferredConnectionParameters = 16,60,0,400
2019-12-21 15:19:07.696793 (BLE2MQTT-8264.lan): I (439942) BLE2MQTT: Publishing: 58:2d:34:36:18:9c/BatteryService/BatteryLevel = 83
2019-12-21 15:19:07.748739 (BLE2MQTT-8264.lan): I (439992) BLE2MQTT: Publishing: 58:2d:34:36:18:9c/DeviceInformation/ManufacturerNameString = Cleargrass Inc
2019-12-21 15:19:07.816586 (BLE2MQTT-8264.lan): I (440062) BLE2MQTT: Publishing: 58:2d:34:36:18:9c/DeviceInformation/ModelNumberString = Duck_Release
Traceback (most recent call last):
  File "remote_log.py", line 66, in <module>
    main()
  File "remote_log.py", line 63, in main
    log_listener(args)
  File "remote_log.py", line 41, in log_listener
    data.decode()), end='')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 102: invalid start byte
`

**Comment by shmuelzon** [comment]
Hey,

All the strings the application creates are all ASCII with the single exception of string values obtained from the BLE peripheral. Those, according to the standard, can be utf-8 or utf-16 but apparently your peripheral is just using the extended ASCII characters and not a valid utf-8. Anyways, I'm forcing decoding as UTF-8 in the python script and ignoring errors so you won't see these kinds of messages.

Thanks
